package com.spark.xposeddy.repository.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.spark.xposeddy.repository.bean.CommentBean;

import com.spark.xposeddy.repository.greendao.CommentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentBeanDaoConfig;

    private final CommentBeanDao commentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentBeanDaoConfig = daoConfigMap.get(CommentBeanDao.class).clone();
        commentBeanDaoConfig.initIdentityScope(type);

        commentBeanDao = new CommentBeanDao(commentBeanDaoConfig, this);

        registerDao(CommentBean.class, commentBeanDao);
    }
    
    public void clear() {
        commentBeanDaoConfig.clearIdentityScope();
    }

    public CommentBeanDao getCommentBeanDao() {
        return commentBeanDao;
    }

}
